ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.transport.server.ApplicationKt.module ]
    }
}

database {
    jdbcUrl = ${?DATABASE_URL}
    maximumPoolSize = 10
}

firebase {
    credentialsFile = ${?FIREBASE_CREDENTIALS_FILE}
    projectId = ${?FIREBASE_PROJECT_ID}
}

admin {
    jwtSecret = "transport-tickets-admin-jwt-secret-2024"
    jwtSecret = ${?ADMIN_JWT_SECRET}
}
