ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.transport.server.ApplicationKt.module ]
    }
}

database {
    jdbcUrl = "jdbc:postgresql://ep-sweet-heart-aqf0c174.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&user=neondb_owner&password=npg_cK7hZ9VXQUJr"
    jdbcUrl = ${?DATABASE_URL}
    maximumPoolSize = 10
}

admin {
    jwtSecret = "transport-tickets-admin-jwt-secret-2024"
    jwtSecret = ${?ADMIN_JWT_SECRET}
}
